services:
  - type: web
    name: vcards
    env: docker
    plan: free
    region: oregon 
    buildCommand: docker build -t vcards .
    startCommand: vcard-entrypoint.sh
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: vcard_db
          property: connectionString
      - key: PORT
        value: 80

databases:
  - name: vcard_db
    plan: free
    region: oregon
