services:
  - type: web
    name: vcards
    env: docker
    plan: free
    region: oregon 
    buildCommand: docker build -t vcards .
    startCommand: ./docker-entrypoint.sh
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: APP_URL
        fromService:
          type: web
          name: vcards
          property: host
      - key: APP_DOMAIN
        fromService:
          type: web
          name: vcards
          property: host
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-royal-scene-aij21vqw-pooler.c-4.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_b3tTORj4FHfL
      - key: DB_SSLMODE
        value: require
      - key: PORT
        value: 80
